// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp2anWjguGLOjwuiASGUxSGVGljReFNJk',
    appId: '1:198255281758:web:617ae6f380ae8876d5d6cf',
    messagingSenderId: '198255281758',
    projectId: 'kingdom-kids-f570b',
    authDomain: 'kingdom-kids-f570b.firebaseapp.com',
    storageBucket: 'kingdom-kids-f570b.firebasestorage.app',
    measurementId: 'G-1HMVVPFVQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlp2rGGZdKzkpFdgmaTgnVICWnaX4cCfE',
    appId: '1:198255281758:android:c1b483e1c6a25f85d5d6cf',
    messagingSenderId: '198255281758',
    projectId: 'kingdom-kids-f570b',
    storageBucket: 'kingdom-kids-f570b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2pYzgW1GTDRdhiW4yG78qOvqc1RpAytY',
    appId: '1:198255281758:ios:17511a5d6b4e09acd5d6cf',
    messagingSenderId: '198255281758',
    projectId: 'kingdom-kids-f570b',
    storageBucket: 'kingdom-kids-f570b.firebasestorage.app',
    iosBundleId: 'com.example.kingdomKidsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2pYzgW1GTDRdhiW4yG78qOvqc1RpAytY',
    appId: '1:198255281758:ios:17511a5d6b4e09acd5d6cf',
    messagingSenderId: '198255281758',
    projectId: 'kingdom-kids-f570b',
    storageBucket: 'kingdom-kids-f570b.firebasestorage.app',
    iosBundleId: 'com.example.kingdomKidsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp2anWjguGLOjwuiASGUxSGVGljReFNJk',
    appId: '1:198255281758:web:873c6569ca3da876d5d6cf',
    messagingSenderId: '198255281758',
    projectId: 'kingdom-kids-f570b',
    authDomain: 'kingdom-kids-f570b.firebaseapp.com',
    storageBucket: 'kingdom-kids-f570b.firebasestorage.app',
    measurementId: 'G-P8MX111VXQ',
  );
}
