services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kingdom_kids
      POSTGRES_PASSWORD: "Xtm8uEAmhx8GO3mBj958Ysfl5XicnRwk"
    volumes:
      - kingdom_kids_data:/var/lib/postgresql/data

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kingdom_kids_test
      POSTGRES_PASSWORD: "bzVmH68bnJLVnSn9oB2-kMAfrdB67GU6"
    volumes:
      - kingdom_kids_test_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  kingdom_kids_data:
  kingdom_kids_test_data:
  minio_data: