name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '4.0.0-beta.0'
      SERVERPOD_PASSWORD_database: 'bzVmH68bnJLVnSn9oB2-kMAfrdB67GU6'
      SERVERPOD_PASSWORD_redis: 'D5tzijOOsuuN9eiGb82NVKlYNI-5k6_5'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.4'

      - name: Start containers
        working-directory: kingdom_kids_server
        run: docker compose up --quiet-pull --build -d

      - name: Install dependencies
        run: flutter pub get

      - name: Install Serverpod CLI
        run: dart install serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: kingdom_kids_server
        run: serverpod generate

      - name: Run tests
        working-directory: kingdom_kids_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: kingdom_kids_server
        run: docker compose down -v
